[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 14

[font.glyph_offset]
y = 2

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
y = 4

[terminal.shell]
args = ["-lic", "tmux new -ADs FreedomKnight"]
program = "/bin/zsh"

[window]
decorations = "transparent"
dynamic_title = false
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2

[general]
live_config_reload = true

[terminal]
